### ISSUE TITLE
[dglo on 2011-08-29 20:21:49] : pDAQ: daq-io - race condition in SimpleOutputEngine

### ISSUE THREAD

**Issue by dglo** [dglo/daq-io#121]
While repeatedly running the unit tests in daq-integration test, I saw this exception twice in EBReadonlyTest:

Exception in thread "globalTrigger-0-globalTriggerOutputEngine" java.lang.NullPointerException
        at icecube.daq.io.SimpleOutputEngine$SimpleOutputChannel.transmit(SimpleOutputEngine.java:908)
        at icecube.daq.io.SimpleOutputEngine.run(SimpleOutputEngine.java:556)
        at java.lang.Thread.run(Thread.java:680)

The offending line is:

    int bytes = channel.write(buf);

and the problem occurs when SimpleOutputChannel.close() is called while the channel is sending output

**Comment by dglo** [comment]
[dglo on 2011-08-29 20:38:04]
svn commit -m"Issue 5136: Setting 'channel' to null causes a race condition; use 'channel.isOpen()' to determine if channel has been closed" src/main/java/icecube/daq/io/SimpleOutputEngine.java 
Sending        src/main/java/icecube/daq/io/SimpleOutputEngine.java
Transmitting file data .
Committed revision 13301.

**Comment by dglo** [comment]
[dglo on 2012-05-10 15:05:18]
These issues are all in releases
